@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 10,
    "backwardDepth": 10,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": false,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 5,
    "showDetailedClassStructure": true
  },
  "rootClass": "br.com.fiap.challenge.domain.entity.Itens",
  "extensionCallbackMethod": "Usuario_structure.puml" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_98689 { 
   	label=com
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_660573057 { 
   	label=fiap
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1205924276 { 
   	label=challenge
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   subgraph cluster_1409545790 { 
   	label=domain
	labeljust=l
	fillcolor="#bababa"
	style=filled
   
   subgraph cluster_1883287955 { 
   	label=entity
	labeljust=l
	fillcolor="#b0b0b0"
	style=filled

Usuario1541195919[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Usuario</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cepEntrega: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   complemento: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cpf: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   logradouro: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   numLogradouro: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   senha: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   telefone: Long [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ setCepEntrega(cepEntrega: Long): Usuario</TD></TR>
<TR><TD ALIGN="LEFT" >+ setComplemento(complemento: String): Usuario</TD></TR>
<TR><TD ALIGN="LEFT" >+ setCpf(cpf: Long): Usuario</TD></TR>
<TR><TD ALIGN="LEFT" >+ setEmail(email: String): Usuario</TD></TR>
<TR><TD ALIGN="LEFT" >+ setLogradouro(logradouro: String): Usuario</TD></TR>
<TR><TD ALIGN="LEFT" >+ setNome(nome: String): Usuario</TD></TR>
<TR><TD ALIGN="LEFT" >+ setNumLogradouro(numLogradouro: int): Usuario</TD></TR>
<TR><TD ALIGN="LEFT" >+ setSenha(senha: String): Usuario</TD></TR>
<TR><TD ALIGN="LEFT" >+ setTelefone(telefone: Long): Usuario</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Compra1541195919[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Compra</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   codContrato: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dataCompra: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   usuario: Usuario [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   valorTotal: BigDecimal [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ setCodContrato(codContrato: String): Compra</TD></TR>
<TR><TD ALIGN="LEFT" >+ setDataCompra(dataCompra: LocalDate): Compra</TD></TR>
<TR><TD ALIGN="LEFT" >+ setId(id: Long): Compra</TD></TR>
<TR><TD ALIGN="LEFT" >+ setUsuario(usuario: Usuario): Compra</TD></TR>
<TR><TD ALIGN="LEFT" >+ setValorTotal(valorTotal: BigDecimal): Compra</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

   CompraItens1541195919[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CompraItens</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   compra: Compra [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   itens: Itens [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   quantidade: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   valor: BigDecimal [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ setCompra(compra: Compra): CompraItens</TD></TR>
<TR><TD ALIGN="LEFT" >+ setItens(itens: Itens): CompraItens</TD></TR>
<TR><TD ALIGN="LEFT" >+ setQuantidade(quantidade: BigDecimal): CompraItens</TD></TR>
<TR><TD ALIGN="LEFT" >+ setValor(valor: BigDecimal): CompraItens</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Fornecedor1541195919[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Fornecedor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cnpj: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   reputacao: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   telefone: Long [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ setCnpj(cnpj: Long): Fornecedor</TD></TR>
<TR><TD ALIGN="LEFT" >+ setNome(nome: String): Fornecedor</TD></TR>
<TR><TD ALIGN="LEFT" >+ setReputacao(reputacao: String): Fornecedor</TD></TR>
<TR><TD ALIGN="LEFT" >+ setTelefone(telefone: Long): Fornecedor</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FornecedorItens1541195919[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FornecedorItens</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   fornecedor: Fornecedor [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   itens: Itens [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   quantidade: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   valor: BigDecimal [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ setFornecedor(fornecedor: Fornecedor): FornecedorItens</TD></TR>
<TR><TD ALIGN="LEFT" >+ setItens(itens: Itens): FornecedorItens</TD></TR>
<TR><TD ALIGN="LEFT" >+ setQuantidade(quantidade: BigDecimal): FornecedorItens</TD></TR>
<TR><TD ALIGN="LEFT" >+ setValor(valor: BigDecimal): FornecedorItens</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Itens1541195919[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Itens</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   descricao: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tipoItem: TipoItem [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ setDescricao(descricao: String): Itens</TD></TR>
<TR><TD ALIGN="LEFT" >+ setId(id: int): Itens</TD></TR>
<TR><TD ALIGN="LEFT" >+ setNome(nome: String): Itens</TD></TR>
<TR><TD ALIGN="LEFT" >+ setTipoItem(tipoItem: TipoItem): Itens</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TipoItem1541195919[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TipoItem</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   descricao: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ setDescricao(descricao: String): TipoItem</TD></TR>
<TR><TD ALIGN="LEFT" >+ setId(id: int): TipoItem</TD></TR>
<TR><TD ALIGN="LEFT" >+ setNome(nome: String): TipoItem</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 
} 
} 
} 

'edges    
Fornecedor1541195919 -> FornecedorItens1541195919[label="fornecedorItens
[0..1]"];
Usuario1541195919 -> Compra1541195919[label="compra
[0..1]"];
Compra1541195919 -> CompraItens1541195919[label="compraItens
[0..1]"];
CompraItens1541195919 -> Itens1541195919[label="itens
[0..1]"];
FornecedorItens1541195919 -> Itens1541195919[label="itens
[0..1]"];
Itens1541195919 -> TipoItem1541195919[label="tipoItem
[0..1]"];
    
}
@enduml